language: ruby
rvm:
- 2.2.5

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
    - gh-pages
      - /pages-(.*)/

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false